services:

  postgres-service:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=articleManagementSystemDB'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  redis-service:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  authentication-service:
    build:
      context: .
      dockerfile: ./authenticationService/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres-service
      - redis-service

  article-service:
    build:
      context: .
      dockerfile: ./articleService/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres-service

  api-gateway-service:
    build:
      context: .
      dockerfile: ./apiGateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - article-service
      - authentication-service